#include<algorithm>
#include<bitset>
#include<complex>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<hash_map>
#include<hash_set>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<iso646.h>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<strstream>
#include<utility>
#include<valarray>
#include<vector>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<cmath>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
using namespace std;
int main()
{
    int n,d,m,y,l,i,j;
    char a[20],b[20],c[20];
    int max=0;
    int min=99999999;
    while(scanf("%d",&n)==1)
    {
        for(j=0;j<n;j++)
        {
            scanf("%s %d %d %d",a,&d,&m,&y);
            l=strlen(a);
            if((y*360+m*30+d)>max)
            {
                max=(y*360+m*30+d);
                for(i=0;i<l;i++)
                {
                    b[i]=a[i];
                }
                b[i]='\0';
            }
            if((y*360+m*30+d)<min)
            {
                min=(y*360+m*30+d);
                for(i=0;i<l;i++)
                {
                    c[i]=a[i];
                }
                c[i]='\0';
            }
        }
        printf("%s\n%s\n",b,c);
    }
    return 0;
}
